import type { NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";

const Home: NextPage = (props) => {
  const { data: session } = useSession();

  return (
    <div className="h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="bg-blue-100 h-14  w-full">
        <div className="flex items-center justify-end">
         
          {!session && (
            <button
              className="text-white py-2 px-4 mt-2 mx-5 bg-slate-400 hover:bg-slate-500 rounded-full"
              onClick={() => signIn()}
            >
              Sign in
            </button>
          )}
        </div>
      </header>

      <main className="h-full">
        {session && (
          <>
            <h2>Olá {session.user?.name}</h2>
            <button className="text-red-300" onClick={() => signOut()}>
              Sign out
            </button>
          </>
        )}
        <h1>Pagina de teste</h1>
      </main>

      <footer className="bg-blue-500 h-10">ssss</footer>
    </div>
  );
};

export default Home;
